import React, { useState, useEffect } from 'react';
import NaturalLanguageSearch from '../components/NaturalLanguageSearch';
import {
  Container,
  Typography,
  Box,
  Paper,
  Button,
  Grid,
  Card,
  CardContent,
  CardActions,
  Chip,
  Alert,
  TextField,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  Tabs,
  Tab,
  LinearProgress,
  IconButton,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  List,
  ListItem,
  ListItemText,
  Divider,
} from '@mui/material';
import {
  Work,
  LocationOn,
  AttachMoney,
  Business,
  Star,
  StarBorder,
  Launch,
  FilterList,
  Refresh,
  TrendingUp,
} from '@mui/icons-material';
