# Cloud Build Configuration for JobBuddy
# Builds, tests, and deploys backend and frontend to GCP Cloud Run
# Region: Belgium (europe-west1)

steps:
  # Backend Steps
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'backend'
    id: 'backend-install'

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'lint']
    dir: 'backend'
    id: 'backend-lint'
    waitFor: ['backend-install']

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'test']
    dir: 'backend'
    id: 'backend-test'
    waitFor: ['backend-install']

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    dir: 'backend'
    id: 'backend-build'
    waitFor: ['backend-lint', 'backend-test']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/jobbuddy-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/jobbuddy-backend:latest'
      - '-f'
      - 'backend/Dockerfile'
      - './backend'
    id: 'backend-docker-build'
    waitFor: ['backend-build']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/jobbuddy-backend:$COMMIT_SHA']
    id: 'backend-docker-push'
    waitFor: ['backend-docker-build']

  # Frontend Steps
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'frontend'
    id: 'frontend-install'

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'lint']
    dir: 'frontend'
    id: 'frontend-lint'
    waitFor: ['frontend-install']

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'test', '--', '--watchAll=false']
    dir: 'frontend'
    id: 'frontend-test'
    waitFor: ['frontend-install']

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    dir: 'frontend'
    env:
      - 'REACT_APP_API_URL=https://jobbuddy-backend-${_REGION}.a.run.app'
    id: 'frontend-build'
    waitFor: ['frontend-lint', 'frontend-test']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/jobbuddy-frontend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/jobbuddy-frontend:latest'
      - '--build-arg'
      - 'REACT_APP_API_URL=https://jobbuddy-backend-${_REGION}.a.run.app'
      - '-f'
      - 'frontend/Dockerfile'
      - './frontend'
    id: 'frontend-docker-build'
    waitFor: ['frontend-build']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/jobbuddy-frontend:$COMMIT_SHA']
    id: 'frontend-docker-push'
    waitFor: ['frontend-docker-build']

  # Deploy Backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'jobbuddy-backend'
      - '--image=gcr.io/$PROJECT_ID/jobbuddy-backend:$COMMIT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--set-env-vars=NODE_ENV=production,PORT=8080'
      - '--set-secrets=DB_PASSWORD=jobbuddy-db-password:latest,JWT_SECRET=jobbuddy-jwt-secret:latest,OPENAI_API_KEY=jobbuddy-openai-key:latest,ENCRYPTION_KEY=jobbuddy-encryption-key:latest'
      - '--add-cloudsql-instances=${_CLOUDSQL_INSTANCE}'
    id: 'deploy-backend'
    waitFor: ['backend-docker-push']

  # Deploy Frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'jobbuddy-frontend'
      - '--image=gcr.io/$PROJECT_ID/jobbuddy-frontend:$COMMIT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=5'
    id: 'deploy-frontend'
    waitFor: ['frontend-docker-push']

  # Run Database Migrations
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run jobs create jobbuddy-migrate-$SHORT_SHA \
          --image=gcr.io/$PROJECT_ID/jobbuddy-backend:$COMMIT_SHA \
          --region=${_REGION} \
          --set-secrets=DB_PASSWORD=jobbuddy-db-password:latest \
          --add-cloudsql-instances=${_CLOUDSQL_INSTANCE} \
          --command=node \
          --args=scripts/migrate.js \
          --execute-now \
          --wait || echo "Migration job completed or already exists"
    id: 'run-migrations'
    waitFor: ['deploy-backend']

# Substitution variables - BELGIAN REGION
substitutions:
  _REGION: 'europe-west1'
  _CLOUDSQL_INSTANCE: 'PROJECT_ID:europe-west1:jobbuddy-db'

# Build options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  timeout: '1800s'
