# Cloud Build Configuration for JobBuddy
# Builds, tests, and deploys backend and frontend to GCP Cloud Run

steps:
  # Backend Steps
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'backend'
    id: 'backend-install'

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'lint']
    dir: 'backend'
    id: 'backend-lint'
    waitFor: ['backend-install']

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'test']
    dir: 'backend'
    id: 'backend-test'
    waitFor: ['backend-install']

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    dir: 'backend'
    id: 'backend-build'
    waitFor: ['backend-lint', 'backend-test']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/jobbuddy-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/jobbuddy-backend:latest'
      - '-f'
      - 'backend/Dockerfile'
      - './backend'
    id: 'backend-docker-build'
    waitFor: ['backend-build']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/jobbuddy-backend:$COMMIT_SHA']
    id: 'backend-docker-push'
    waitFor: ['backend-docker-build']

  # Frontend Steps
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'frontend'
    id: 'frontend-install'

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'lint']
    dir: 'frontend'
    id: 'frontend-lint'
    waitFor: ['frontend-install']

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'test', '--', '--watchAll=false']
    dir: 'frontend'
    id: 'frontend-test'
    waitFor: ['frontend-install']

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    dir: 'frontend'
    env:
      - 'REACT_APP_API_URL=https://jobbuddy-backend-${_REGION}.a.run.app'
    id: 'frontend-build'
    waitFor: ['frontend-lint', 'frontend-test']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/jobbuddy-frontend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/jobbuddy-frontend:latest'
      - '--build-arg'
      - 'REACT_APP_API_URL=https://jobbuddy-backend-${_REGION}.a.run.app'
      - '-f'
      - 'frontend/Dockerfile'
      - './frontend'
    id: 'frontend-docker-build'
    waitFor: ['frontend-build']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/jobbuddy-frontend:$COMMIT_SHA']
    id: 'frontend-docker-push'
    waitFor: ['frontend-docker-build']
